[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-trading-indicators"
version = "0.1.0"
description = "A Python package for analyzing trading indicators from ticker data."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
authors = [
    { name = "Robert Boivin", email = "poivronjaune@gmail.com" }
]
keywords = ["trading", "indicators", "finance", "technical-analysis"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Financial and Insurance Industry",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas>=2.0",
    "numpy>=1.25",
    "matplotlib>=3.7",
    "scipy>=1.11",
    "click>=8.1",         # CLI handling
    "tabulate>=0.9",      # optional pretty-print of results
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "mypy>=1.5",
    "black>=23.0",
    "ruff>=0.1.5",
    "pre-commit>=3.3",
]

[project.scripts]
indicators = "ind.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
ignore = ["E501"]
